# GitHub Labels 配置（导出于 2026-05-07）
# 同步工具：https://github.com/EndBug/label-sync 或 https://github.com/crazy-max/ghaction-github-labeler

- name: 'bug'
  description: "Something isn't working"
  color: 'd73a4a'
- name: 'documentation'
  description: 'Improvements or additions to documentation'
  color: '0075ca'
- name: 'duplicate'
  description: 'This issue or pull request already exists'
  color: 'cfd3d7'
- name: 'enhancement'
  description: 'New feature or request'
  color: 'a2eeef'
- name: 'good first issue'
  description: 'Good for newcomers'
  color: '7057ff'
- name: 'help wanted'
  description: 'Extra attention is needed'
  color: '008672'
- name: 'invalid'
  description: "This doesn't seem right"
  color: 'e4e669'
- name: 'question'
  description: 'Further information is requested'
  color: 'd876e3'
- name: 'wontfix'
  description: 'This will not be worked on'
  color: 'ffffff'
